version: '3.8'
services:
  onclick-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      // add the env variables here convert 'key= value' to 'key: 'value'

    depends_on:
      - onclick-postgres
      - onclick-redis

  onclick-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: onclick-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: onclick
    volumes:
      - onclick-postgres-data:/var/lib/postgresql/data

  onclick-redis:
    image: redis:alpine
    ports:
      - "6378:6379"

volumes:
  onclick-postgres-data:
