#!/usr/bin/env bash

# Attempt to create the PostgreSQL database 'onclick'
# This command tries to create the database and suppresses the error if it already exists.
DB_NAME=onclick
DB_USER=postgres

# Check if the database exists
if psql -lqt | cut -d \| -f 1 | grep -qw $DB_NAME; then
    echo "Database $DB_NAME already exists."
else
    sudo -u $DB_USER psql -c "CREATE DATABASE $DB_NAME;"
fi

cd src/models 

npx prisma generate

npx prisma migrate dev --name init
